DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'onboarding_events'
  ) THEN
    CREATE TABLE public.onboarding_events (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
      event text NOT NULL,
      payload jsonb NOT NULL DEFAULT '{}'::jsonb,
      created_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS onboarding_events_user_created_at_idx
      ON public.onboarding_events (user_id, created_at DESC);

    CREATE INDEX IF NOT EXISTS onboarding_events_user_event_idx
      ON public.onboarding_events (user_id, event);
  END IF;
END $$;

ALTER TABLE public.onboarding_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS onboarding_events_select_self ON public.onboarding_events;
CREATE POLICY onboarding_events_select_self
ON public.onboarding_events
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS onboarding_events_insert_self ON public.onboarding_events;
CREATE POLICY onboarding_events_insert_self
ON public.onboarding_events
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

REVOKE ALL ON TABLE public.onboarding_events FROM anon;
REVOKE ALL ON TABLE public.onboarding_events FROM authenticated;
GRANT SELECT, INSERT ON TABLE public.onboarding_events TO authenticated;
